name: curl_parser
description: Parse cURL command to Dart object and convert Dart object to cURL command.
version: 0.1.0
homepage: https://github.com/foss42/apidash/tree/main/packages/curl_parser
repository: https://github.com/foss42/apidash/tree/main/packages/curl_parser
issue_tracker: https://github.com/foss42/apidash/issues
documentation: https://github.com/foss42/apidash/tree/main/packages/curl_parser

topics:
  - curl
  - api
  - rest
  - http
  - network

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.5.0
  equatable: ^2.0.5
  shlex: ^2.0.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.4
