name: better_networking
description: "Simplified Networking. Support for sending REST & GraphQL API Requests."
version: 0.0.1
homepage: https://github.com/foss42/apidash

topics:
  - networking
  - api
  - rest
  - http
  - graphql

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  http: ^1.3.0
  http_parser: ^4.1.2
  json5: ^0.8.2
  json_annotation: ^4.9.0
  seed: ^0.0.3
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  test: ^1.25.2
