name: apidash
description: API Dash is a beautiful open-source cross-platform API Client built using Flutter which can help you easily create & customize your API requests, visually inspect responses and generate Dart code on the go.
publish_to: "none"
version: 0.4.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  multi_split_view: ^2.4.0
  url_launcher: ^6.2.5
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  uuid: ^4.3.3
  davi: ^3.4.1
  http_parser: ^4.0.2
  collection: ^1.17.2
  google_fonts: ^6.2.1
  highlighter: ^0.1.1
  xml: ^6.3.0
  jinja: ^0.5.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  hive_flutter: ^1.1.0
  lottie: ^3.1.0
  mime_dart: ^3.0.0
  path_provider: ^2.1.2
  window_manager: ^0.3.8
  path: ^1.8.3
  flutter_markdown: ^0.6.21
  markdown: ^7.2.2
  just_audio: ^0.9.34
  just_audio_mpv: ^0.1.7
  just_audio_windows: ^0.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  printing: ^5.12.0
  package_info_plus: ^5.0.1
  flutter_typeahead: ^5.2.0
  provider: ^6.1.2
  json_data_explorer:
    git:
      url: https://github.com/foss42/json_data_explorer.git
      ref: b7dde2f85dff4f482eed7eda4ef2a71344ef8b3a
  scrollable_positioned_list: ^0.3.8
  file_picker: ^6.2.0
  flutter_svg: ^2.0.10+1
  vector_graphics_compiler: ^1.1.9+1
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  json_text_field: ^1.1.0
  csv: ^6.0.0
  dio: ^5.4.1

dependency_overrides:
  web: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.9
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
    - assets/intro/
