name: apidash
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  multi_split_view: ^2.4.0
  desktop_window: ^0.4.0
  url_launcher: ^6.1.10
  flutter_riverpod: ^2.1.3
  uuid: ^3.0.7
  davi: ^3.2.0
  http: ^0.13.5
  http_parser: ^4.0.2
  collection: ^1.17.0
  google_fonts: ^4.0.3
  highlighter: ^0.1.1
  string_scanner: ^1.2.0
  xml: ^6.2.2
  jinja: ^0.4.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sending.gif