name: apidash
description: API Dash is a beautiful open-source cross-platform API Client built using Flutter which can help you easily create & customize your API requests, visually inspect responses and generate Dart code on the go.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  multi_split_view: ^2.4.0
  url_launcher: ^6.1.10
  flutter_riverpod: ^2.1.3
  uuid: ^3.0.7
  davi: ^3.2.0
  http: ^0.13.5
  http_parser: ^4.0.2
  collection: ^1.17.0
  google_fonts: ^4.0.3
  highlighter: ^0.1.1
  xml: ^6.2.2
  jinja: ^0.4.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  hive_flutter: ^1.1.0
  lottie: ^2.3.2
  mime_dart: ^3.0.0
  path_provider: ^2.0.14
  window_manager: ^0.3.2
  path: ^1.8.2
  flutter_markdown: ^0.6.14
  markdown: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  test: ^1.22.0
  
flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
