name: genai
description: "A unified Dart/Flutter package for working with multiple Generative AI providers (Google Gemini, OpenAI, Anthropic, Azure OpenAI, Ollama, etc.) using a single request model."
version: 0.0.2-dev
homepage: https://github.com/foss42/apidash/tree/main/packages/genai

topics:
  - ai
  - ollama
  - gemini
  - claude
  - openai

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  better_networking:
    path: ../better_networking
  json_annotation: ^4.9.0
  nanoid: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  freezed: ^3.2.5
  json_serializable: ^6.7.1
  test: ^1.25.2
