name: hurl_parser
description: Parse Hurl files to Dart objects.
version: 0.0.1
homepage: https://github.com/foss42/apidash
repository: https://github.com/foss42/apidash

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  petitparser: ^6.0.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.4
