name: apidash_core
description: "API Dash Core"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  curl_parser:
    path: ../curl_parser
  freezed_annotation: ^2.4.1
  http: ^1.3.0
  http_parser: ^4.1.2
  insomnia_collection:
    path: ../insomnia_collection
  postman:
    path: ../postman
  seed: ^0.0.3
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  test: ^1.25.2
