name: insomnia_collection
description: Seamlessly convert Insomnia Collection Format v4 to Dart.
version: 0.0.2-dev
homepage: https://github.com/foss42/apidash

topics:
  - insomnia
  - api
  - rest
  - http
  - network

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.11.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  lints: ^6.1.0
  test: ^1.24.0
